name: ai_management_app
description: A Flutter App for managing AI models

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  go_router: ^13.2.0
  grpc: ^3.2.4
  protobuf: ^3.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
